"""
Choose which test films the DVC pipeline runs.

films.yaml lists every test film; this tool copies the chosen ones into
selection.yaml, which dvc.yaml loads through `vars`. Films left out keep
their earlier results in the DVC cache: selecting them again restores those
results instead of recomputing them (DVC's run cache), unless their inputs
or the code changed.

Usage:
  python pick_films.py                       # window with a checkbox per film
  python pick_films.py dog-man-2025 [...]    # write the selection, no window
"""

import os
import queue
import subprocess
import sys
import threading
from pathlib import Path

import yaml

LAB = Path(__file__).resolve().parent
CATALOG = LAB / "films.yaml"
SELECTION = LAB / "selection.yaml"

HEADER = """\
# Generated by pick_films.py from films.yaml; do not edit by hand.
# The films that dvc.yaml runs (loaded through `vars`).
"""


def load_catalog():
    with open(CATALOG, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_selected():
    if not SELECTION.exists():
        return []
    with open(SELECTION, encoding="utf-8") as f:
        return list((yaml.safe_load(f) or {}).get("films") or {})


def write_selection(ids):
    catalog = load_catalog()
    unknown = [i for i in ids if i not in catalog]
    if unknown:
        raise SystemExit(f"not in films.yaml: {', '.join(unknown)}")
    if not ids:
        raise SystemExit("select at least one film")
    # Keep catalog order so selection.yaml diffs stay stable.
    films = {k: v for k, v in catalog.items() if k in ids}
    with open(SELECTION, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        yaml.safe_dump({"films": films}, f, sort_keys=False, allow_unicode=True)


def dvc_env():
    """Stage commands call `python` and `whisperx`: use this interpreter's."""
    env = os.environ.copy()
    scripts = str(Path(sys.executable).parent)
    env["PATH"] = scripts + os.pathsep + env.get("PATH", "")
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def gui():
    import tkinter as tk
    from tkinter import messagebox

    catalog = load_catalog()
    selected = set(load_selected())

    root = tk.Tk()
    root.title("SubRetime lab: films")

    tk.Label(root, text="Films to run (films.yaml)").grid(
        row=0, column=0, columnspan=2, padx=8, pady=(8, 2), sticky="w")
    checks = {}
    for row, (film, info) in enumerate(catalog.items(), start=1):
        checks[film] = tk.BooleanVar(value=film in selected)
        tk.Checkbutton(root, text=film, variable=checks[film]).grid(
            row=row, column=0, padx=8, sticky="w")
        tk.Label(root, text=Path(str(info.get("video", ""))).name, fg="gray").grid(
            row=row, column=1, padx=(2, 10), sticky="w")

    buttons = tk.Frame(root)
    buttons.grid(row=len(catalog) + 1, column=0, columnspan=2, pady=8)
    log = tk.Text(root, width=100, height=20, wrap="none", state="disabled")
    log.grid(row=len(catalog) + 2, column=0, columnspan=2, padx=8, pady=(0, 8))

    def append(text):
        log.configure(state="normal")
        log.insert(tk.END, text)
        log.see(tk.END)
        log.configure(state="disabled")

    def save():
        ids = [f for f, v in checks.items() if v.get()]
        if not ids:
            messagebox.showerror("Error", "Select at least one film.")
            return False
        write_selection(ids)
        append(f"selection.yaml: {', '.join(ids)}\n")
        return True

    lines = queue.Queue()

    def run():
        if not save():
            return
        cmd = [sys.executable, "-m", "dvc", "repro"]
        append("> dvc repro\n")
        run_button.configure(state="disabled", text="Running…")

        def work():
            # No Tk calls here: Tk is not thread-safe. Lines go through the
            # queue; the Tk thread polls it in poll().
            try:
                proc = subprocess.Popen(
                    cmd, cwd=LAB, env=dvc_env(), stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT, text=True, encoding="utf-8",
                    errors="replace")
                for line in proc.stdout:
                    lines.put(line)
                lines.put((proc.wait(),))
            except Exception as e:
                lines.put(f"{e}\n")
                lines.put((1,))

        def poll():
            while True:
                try:
                    item = lines.get_nowait()
                except queue.Empty:
                    root.after(200, poll)
                    return
                if isinstance(item, tuple):
                    append(f"exit code {item[0]}\n")
                    run_button.configure(state="normal", text="Save and run dvc repro")
                    return
                append(item)

        threading.Thread(target=work, daemon=True).start()
        root.after(200, poll)

    tk.Button(buttons, text="Save selection", command=save, width=20).pack(
        side="left", padx=6)
    run_button = tk.Button(buttons, text="Save and run dvc repro", command=run,
                           width=24)
    run_button.pack(side="left", padx=6)

    root.mainloop()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        write_selection(sys.argv[1:])
        print(f"selection.yaml: {', '.join(sys.argv[1:])}")
    else:
        gui()
