"""
Choose which test films the DVC pipeline runs.

films.yaml lists every test film; this tool copies the chosen ones into
selection.yaml, which dvc.yaml loads through `vars`. Films left out keep
their earlier results in the DVC cache: selecting them again restores those
results instead of recomputing them (DVC's run cache), unless their inputs
or the code changed.

Usage:
  python pick_films.py                       # window: a checkbox per films/ folder
  python pick_films.py dog-man-2025 [...]    # write the selection, no window
"""

import os
import queue
import subprocess
import sys
import threading
from pathlib import Path

import yaml

LAB = Path(__file__).resolve().parent
CATALOG = LAB / "films.yaml"
FILMS = LAB / "films"
SELECTION = LAB / "selection.yaml"

HEADER = """\
# Generated by pick_films.py from films.yaml; do not edit by hand.
# The films that dvc.yaml runs (loaded through `vars`); `transcribe` holds
# those without a transcript of their own.
"""


def load_catalog():
    with open(CATALOG, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_selected():
    if not SELECTION.exists():
        return []
    with open(SELECTION, encoding="utf-8") as f:
        return list((yaml.safe_load(f) or {}).get("films") or {})


def write_selection(ids):
    catalog = load_catalog()
    unknown = [i for i in ids if i not in catalog]
    if unknown:
        raise SystemExit(f"not in films.yaml: {', '.join(unknown)}")
    if not ids:
        raise SystemExit("select at least one film")
    # Keep catalog order so selection.yaml diffs stay stable. A film without
    # its own `whisper` transcript (a sample cut by make_sample.py has one)
    # is transcribed into work/<film>/whisper: it goes into `transcribe`,
    # the list the transcribe stage runs over.
    films, transcribe = {}, {}
    for film, info in catalog.items():
        if film not in ids:
            continue
        if "whisper" not in info:
            info = {**info, "whisper": f"work/{film}/whisper"}
            transcribe[film] = info
        films[film] = info
    with open(SELECTION, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        yaml.safe_dump({"films": films, "transcribe": transcribe}, f,
                       sort_keys=False, allow_unicode=True)


def dvc_env():
    """Stage commands call `python` and `whisperx`: use this interpreter's."""
    env = os.environ.copy()
    scripts = str(Path(sys.executable).parent)
    env["PATH"] = scripts + os.pathsep + env.get("PATH", "")
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def gui():
    import tkinter as tk
    from tkinter import messagebox

    catalog = load_catalog()
    selected = set(load_selected())
    # One row per folder in films/, in catalog order; a folder films.yaml
    # does not describe yet is shown but cannot be chosen.
    folders = sorted(p.name for p in FILMS.iterdir() if p.is_dir())
    rows = [f for f in catalog if f in folders] + [f for f in folders if f not in catalog]

    root = tk.Tk()
    root.title("SubRetime lab: films")

    tk.Label(root, text="Films to run (folders in lab/films/)").grid(
        row=0, column=0, columnspan=2, padx=8, pady=(8, 2), sticky="w")
    checks = {}
    for row, film in enumerate(rows, start=1):
        info = catalog.get(film)
        var = tk.BooleanVar(value=film in selected)
        box = tk.Checkbutton(root, text=film, variable=var)
        box.grid(row=row, column=0, padx=8, sticky="w")
        if info is None:
            box.configure(state="disabled")
            note = "not in films.yaml"
        else:
            checks[film] = var
            note = Path(str(info.get("video", ""))).name
            if "whisper" in info:
                note += "  (transcript cut from the film's)"
        tk.Label(root, text=note, fg="gray").grid(
            row=row, column=1, padx=(2, 10), sticky="w")

    def check_all(value):
        for var in checks.values():
            var.set(value)

    buttons = tk.Frame(root)
    buttons.grid(row=len(rows) + 1, column=0, columnspan=2, pady=8)
    log = tk.Text(root, width=100, height=20, wrap="none", state="disabled")
    log.grid(row=len(rows) + 2, column=0, columnspan=2, padx=8, pady=(0, 8))

    def append(text):
        log.configure(state="normal")
        log.insert(tk.END, text)
        log.see(tk.END)
        log.configure(state="disabled")

    def save():
        ids = [f for f, v in checks.items() if v.get()]
        if not ids:
            messagebox.showerror("Error", "Select at least one film.")
            return False
        write_selection(ids)
        append(f"selection.yaml: {', '.join(ids)}\n")
        return True

    lines = queue.Queue()

    def run():
        if not save():
            return
        cmd = [sys.executable, "-m", "dvc", "repro"]
        append("> dvc repro\n")
        run_button.configure(state="disabled", text="Running…")

        def work():
            # No Tk calls here: Tk is not thread-safe. Lines go through the
            # queue; the Tk thread polls it in poll().
            try:
                proc = subprocess.Popen(
                    cmd, cwd=LAB, env=dvc_env(), stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT, text=True, encoding="utf-8",
                    errors="replace")
                for line in proc.stdout:
                    lines.put(line)
                lines.put((proc.wait(),))
            except Exception as e:
                lines.put(f"{e}\n")
                lines.put((1,))

        def poll():
            while True:
                try:
                    item = lines.get_nowait()
                except queue.Empty:
                    root.after(200, poll)
                    return
                if isinstance(item, tuple):
                    append(f"exit code {item[0]}\n")
                    run_button.configure(state="normal", text="Save and run dvc repro")
                    return
                append(item)

        threading.Thread(target=work, daemon=True).start()
        root.after(200, poll)

    tk.Button(buttons, text="All", command=lambda: check_all(True), width=6).pack(
        side="left", padx=6)
    tk.Button(buttons, text="None", command=lambda: check_all(False), width=6).pack(
        side="left", padx=6)
    tk.Button(buttons, text="Save selection", command=save, width=20).pack(
        side="left", padx=6)
    run_button = tk.Button(buttons, text="Save and run dvc repro", command=run,
                           width=24)
    run_button.pack(side="left", padx=6)

    root.mainloop()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        write_selection(sys.argv[1:])
        print(f"selection.yaml: {', '.join(sys.argv[1:])}")
    else:
        gui()
