"""
Choose which test films the DVC pipeline runs.

films.yaml lists every test film; this tool copies the chosen ones into
selection.yaml, which dvc.yaml loads through `vars`. Films left out keep
their earlier results in the DVC cache: selecting them again restores those
results instead of recomputing them (DVC's run cache), unless their inputs
or the code changed.

Usage:
  python pick_films.py                       # window: a checkbox per films/ folder
  python pick_films.py dog-man-2025 [...]    # write the selection, no window
"""

import json
import os
import queue
import re
import subprocess
import sys
import threading
from pathlib import Path

import yaml

LAB = Path(__file__).resolve().parent
CATALOG = LAB / "films.yaml"
FILMS = LAB / "films"
SELECTION = LAB / "selection.yaml"

HEADER = """\
# Generated by pick_films.py from films.yaml; do not edit by hand.
# The films that dvc.yaml runs (loaded through `vars`); `transcribe` holds
# those without a transcript of their own.
"""


# Shown in the window's log area until the first log line replaces it.
HELP = """\
Save selection
  Writes the ticked films to selection.yaml: the films `dvc repro` runs,
  and the ones debug_film.py offers to debug.

Save and run dvc repro
  Saves, then runs the pipeline on the ticked films (transcribe -> align ->
  evaluate) and shows its output here. Stages whose inputs and code have
  not changed are skipped. It produces what debugging needs:
    - the WhisperX transcript (without it a film cannot be debugged)
    - the audio cache, cache/<film>/ (without it the debugger loads the
      video and the GPU model)
    - the step snapshots, out/<film>/steps/, to compare with while debugging
  Wait for "exit code" before closing the window.

Opened from the debugger (debug_film.py, answer p): Save selection, or a
successful Save and run dvc repro, closes the window and returns to the film
list in the terminal. The pipeline never pauses at stops.yaml's stops.

Choose video... adds a films/ folder that films.yaml does not describe yet.
"""


def load_catalog():
    with open(CATALOG, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_selected():
    if not SELECTION.exists():
        return []
    with open(SELECTION, encoding="utf-8") as f:
        return list((yaml.safe_load(f) or {}).get("films") or {})


def yaml_path(path):
    """A path for films.yaml: relative to lab/ when under it, forward
    slashes, double-quoted (a JSON string is a valid YAML scalar)."""
    path = Path(path).resolve()
    try:
        path = path.relative_to(LAB)
    except ValueError:
        pass
    return json.dumps(path.as_posix(), ensure_ascii=False)


def register_film(film, video, baseline):
    """Append an entry for films/<film> to films.yaml as text, so the
    comments in the file survive (yaml.safe_dump would drop them)."""
    folder = FILMS / film
    key = film if re.fullmatch(r"[\w.-]+", film) else json.dumps(film, ensure_ascii=False)
    entry = [f"{key}:",
             f"  video: {yaml_path(video)}",
             f"  original: {yaml_path(folder / 'original.srt')}",
             f"  baseline: {yaml_path(baseline)}"]
    if (folder / "whisper").is_dir():
        entry.append(f"  whisper: {yaml_path(folder / 'whisper')}")
    text = CATALOG.read_text(encoding="utf-8")
    with open(CATALOG, "a", encoding="utf-8", newline="\n") as f:
        if text and not text.endswith("\n"):
            f.write("\n")
        f.write("\n".join(entry) + "\n")


def write_selection(ids):
    catalog = load_catalog()
    unknown = [i for i in ids if i not in catalog]
    if unknown:
        raise SystemExit(f"not in films.yaml: {', '.join(unknown)}")
    if not ids:
        raise SystemExit("select at least one film")
    # Keep catalog order so selection.yaml diffs stay stable. A film without
    # its own `whisper` transcript (a sample cut by make_sample.py has one)
    # is transcribed into work/<film>/whisper: it goes into `transcribe`,
    # the list the transcribe stage runs over.
    films, transcribe = {}, {}
    for film, info in catalog.items():
        if film not in ids:
            continue
        if "whisper" not in info:
            info = {**info, "whisper": f"work/{film}/whisper"}
            transcribe[film] = info
        films[film] = info
    with open(SELECTION, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        yaml.safe_dump({"films": films, "transcribe": transcribe}, f,
                       sort_keys=False, allow_unicode=True)


def dvc_env():
    """Stage commands call `python` and `whisperx`: use this interpreter's."""
    env = os.environ.copy()
    scripts = str(Path(sys.executable).parent)
    env["PATH"] = scripts + os.pathsep + env.get("PATH", "")
    env["PYTHONIOENCODING"] = "utf-8"
    # Opened from debug_film.py under the debugger: the stages must not
    # pause at an invisible pdb prompt (see dev_stops.py).
    env.pop("SUBRETIME_STOPS", None)
    return env


def gui(from_debugger=False):
    """from_debugger: opened by debug_film.py, which waits for the window to
    close; saving (or a successful run) closes it."""
    import tkinter as tk
    from tkinter import filedialog, messagebox

    catalog = load_catalog()
    selected = set(load_selected())
    # One row per folder in films/, in catalog order; a folder films.yaml
    # does not describe yet gets a "Choose video…" button that registers it.
    folders = sorted(p.name for p in FILMS.iterdir() if p.is_dir())
    rows = [f for f in catalog if f in folders] + [f for f in folders if f not in catalog]

    root = tk.Tk()
    root.title("SubRetime lab: films" + (" (saving returns to the debugger)"
                                         if from_debugger else ""))

    tk.Label(root, text="Films to run (folders in lab/films/)").grid(
        row=0, column=0, columnspan=3, padx=8, pady=(8, 2), sticky="w")
    checks = {}

    def describe(info):
        note = Path(str(info.get("video", ""))).name
        if "whisper" in info:
            note += "  (transcript cut from the film's)"
        return note

    def choose_video(film, box, var, label, button):
        folder = FILMS / film
        video = filedialog.askopenfilename(
            parent=root, title=f"Video for {film}", filetypes=[
                ("Video / audio", "*.mp4 *.mkv *.avi *.mov *.m4a *.mp3 *.wav"),
                ("All files", "*.*")])
        if not video:
            return
        if not (folder / "original.srt").is_file():
            messagebox.showerror(
                "Error", f"films/{film}/original.srt is missing: put the "
                "subtitle to retime there first.", parent=root)
            return
        baseline = folder / "ffsubsync.srt"
        if not baseline.is_file():
            # Without a baseline of its own the film is evaluated against
            # its original subtitle, unless another .srt is chosen.
            chosen = ""
            if messagebox.askyesno(
                    "No baseline", f"films/{film}/ffsubsync.srt is missing. "
                    "Choose another .srt as the baseline (the reference "
                    "timeline for evaluate_timing.py)?\n\n"
                    "No: use original.srt as the baseline.", parent=root):
                chosen = filedialog.askopenfilename(
                    parent=root, title=f"Baseline for {film}", initialdir=folder,
                    filetypes=[("Subtitles", "*.srt"), ("All files", "*.*")])
            baseline = chosen or folder / "original.srt"
        register_film(film, video, baseline)
        info = load_catalog()[film]
        catalog[film] = info
        checks[film] = var
        box.configure(state="normal")
        label.configure(text=describe(info))
        button.destroy()
        append(f"films.yaml: added {film}\n")

    for row, film in enumerate(rows, start=1):
        info = catalog.get(film)
        var = tk.BooleanVar(value=film in selected)
        box = tk.Checkbutton(root, text=film, variable=var)
        box.grid(row=row, column=0, padx=8, sticky="w")
        label = tk.Label(root, fg="gray")
        label.grid(row=row, column=1, padx=(2, 10), sticky="w")
        if info is None:
            box.configure(state="disabled")
            label.configure(text="not in films.yaml")
            button = tk.Button(root, text="Choose video…")
            button.configure(command=lambda f=film, b=box, v=var, l=label, btn=button:
                             choose_video(f, b, v, l, btn))
            button.grid(row=row, column=2, padx=(0, 8), sticky="w")
        else:
            checks[film] = var
            label.configure(text=describe(info))

    def check_all(value):
        for var in checks.values():
            var.set(value)

    buttons = tk.Frame(root)
    buttons.grid(row=len(rows) + 1, column=0, columnspan=3, pady=8)
    log = tk.Text(root, width=100, height=20, wrap="none", state="disabled")
    log.grid(row=len(rows) + 2, column=0, columnspan=3, padx=8, pady=(0, 8))
    # Until the first log line, the log area explains the buttons.
    log.tag_configure("help", foreground="gray")
    log.configure(state="normal")
    log.insert(tk.END, HELP, "help")
    log.configure(state="disabled")
    showing_help = [True]

    def append(text):
        log.configure(state="normal")
        if showing_help[0]:
            log.delete("1.0", tk.END)
            showing_help[0] = False
        log.insert(tk.END, text)
        log.see(tk.END)
        log.configure(state="disabled")

    def save():
        ids = [f for f, v in checks.items() if v.get()]
        if not ids:
            messagebox.showerror("Error", "Select at least one film.")
            return False
        write_selection(ids)
        append(f"selection.yaml: {', '.join(ids)}\n")
        return True

    lines = queue.Queue()

    def run():
        if not save():
            return
        cmd = [sys.executable, "-m", "dvc", "repro"]
        append("> dvc repro\n")
        run_button.configure(state="disabled", text="Running…")

        def work():
            # No Tk calls here: Tk is not thread-safe. Lines go through the
            # queue; the Tk thread polls it in poll().
            try:
                proc = subprocess.Popen(
                    cmd, cwd=LAB, env=dvc_env(), stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT, text=True, encoding="utf-8",
                    errors="replace")
                for line in proc.stdout:
                    lines.put(line)
                lines.put((proc.wait(),))
            except Exception as e:
                lines.put(f"{e}\n")
                lines.put((1,))

        def poll():
            while True:
                try:
                    item = lines.get_nowait()
                except queue.Empty:
                    root.after(200, poll)
                    return
                if isinstance(item, tuple):
                    append(f"exit code {item[0]}\n")
                    run_button.configure(state="normal", text="Save and run dvc repro")
                    if from_debugger and item[0] == 0:
                        root.after(1500, root.destroy)  # let the result show
                    return
                append(item)

        threading.Thread(target=work, daemon=True).start()
        root.after(200, poll)

    tk.Button(buttons, text="All", command=lambda: check_all(True), width=6).pack(
        side="left", padx=6)
    tk.Button(buttons, text="None", command=lambda: check_all(False), width=6).pack(
        side="left", padx=6)
    def save_clicked():
        if save() and from_debugger:
            root.destroy()

    tk.Button(buttons, text="Save selection", command=save_clicked, width=20).pack(
        side="left", padx=6)
    run_button = tk.Button(buttons, text="Save and run dvc repro", command=run,
                           width=24)
    run_button.pack(side="left", padx=6)

    root.mainloop()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        write_selection(sys.argv[1:])
        print(f"selection.yaml: {', '.join(sys.argv[1:])}")
    else:
        gui()
